apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-data-consumer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-data-consumer1
  template:
    metadata:
      labels:
        app: fake-data-consumer1
    spec:
      containers:
        - name: consumer1
          image: 192.168.1.174:5000/kafka-fake-data-consumer1:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: kafka-app-config
                  key: KAFKA_BOOTSTRAP_SERVER
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-app-config
                  key: KAFKA_TOPIC
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: kafka-app-config
                  key: LOG_LEVEL
